sudo: required
services:
- docker
env:
  COMPOSE_VERSION: 1.4.1
  global:
    DEBUG: False
    PORT: 8000
    LOCAL_IP: "192.168.88.107"
    # secure: PDsk1KlYOoxQzCdx97rEjQ4MYJXHzeyIx9XP6WxbS+EpjGxxHKxeBgxSK3dsE2LHNmFlviABVJTPs0XJ59mKmvIg745aoNoWZZnkrXAwG3K3Om2JibsE6Ja9lYMhO296MFez5jMEiQc39JeWR5GiQU167U+XyLB7ereaqTjRg5hDExLNJyxdz0cOTiwqtquHn52nuIpIwVStBw/DqvHqLIMqkAJAosu4j7moZ4y1CYJcZbYxaf2B/rqHgldYmy+m7v0NnXfFJtDTplCUlHho7k4iYDx3Qz2pQbPiIgbGDa8hIdn9kBAXkfHo0gP4u6Dy7sSYATU4pk9nA9Ikghnh6IwwpLi4rgL8m1Mfp6q/fspkRaWHeqav86NBmBU4PHZ2wJguCwx5PgEesm38HOC+ptiWTAsaplhThzaSjW6guDfTFNQnDAb4HsZaUAzXfC9zZo5f4aExfLJe96+kfbx9SVzSH61VRB0nlXY20CNQI8mBgg1ap+sOlJtsO+exAssvoKYG2y7XgrxEz4aKP54Ekzaji1MKjFhVe2YElnnkNeSvh2hkSsl/w0dh6pcUjGUTxPilUy8V6+2nTie6DZW/DYeaKq9Jqu5noQurXrLQVMyTuidcp7n/YXIUFEGNxb02LQ6tiPQZqpQClyon+UXu0NjiOOHUmiiqtKWY2dgRgQc=
before_install:
- curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
script:
- cd django
- ls
- echo "$SECRET_KEY"
- echo "$PORT"
- docker-compose build
# - docker-compose run web python manage.py test

# deploy:
#   provider: heroku
#   app: budikpet-zoo-prague
#   api_key:
#     secure: TfSM4HUbo5nRHhjHWp2o6MANZUwpSsoc0ddeOKEnBxPRUKSvkqrVj/ysfWR2fxq/e8gZv6YA2pOVRw9rC2iDsHepHG3X7i1Gz7Ok6WiN2CVHWeVlOlaRA2Chf0eLPl9FSJbYwK6k+tHQs/1Iqm9na7GTz5DgW4gHIuqi30YmdpsOQ/oup4eusq/VnYUGsTxlnyt7mhleqiETB2IGvt6ZmjyNeHDPMZ84TtS5ovwZiZXgTPTMY0S4ufF1kZUTodnlYdnQbz4cNNuL9kDsXQjIZuDfvGfS3ruC0zQbRM9X1qUdoTwdlGIJf4eXcXwXW2VAUFKAYgaJXUA8nWEP8YfeFd2SaejM+oh1ycMfHt28Ng//IkGXj9Ozz0kgT+8rtxlnqztJzAvGq0z8hz+aUeX6hU+A0scvrrVZfyCB7mWY8lQZuWXaNW+JELl59LpgCWjdiO4p4j2/VBBOQ7NY37J5Ex2Nr7qxLoJ8wwrXwOeYWwwZLVweAENS7Qm/wMDw8Rv/ng5xVUUw2WQkBdu+O/6dFV2tsTh7E5O1Cypa3fBcYGimidtgGM0HtAG30jLCArVVkLFHRV4DAGrKl9VWtMKQKJXcJ81WFd5Dyp3mya+JlPwJD6VTa8tOuYgKCK/tKZ05fpHnXPXdc45dBa9/FoZFJVDaduus7YWhqYz+MC/saZo=
#   on:
#     # CI is already triggered on all branches, this triggers CD on all branches if CI was OK
#     all_branches: true
