sudo: required
services:
- docker
env:
  COMPOSE_VERSION: 1.28.5
  HEROKU_APP: intelligent-building-django
  global:
    DEBUG: false
    PORT: 8000
    LOCAL_IP: 192.168.88.107
before_install:
- cd django
- curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .env.enc -out .env -d
- curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
script:
- docker-compose build
- docker-compose run web python manage.py makemigrations
- docker-compose run web python manage.py test

deploy:
  skip_cleanup: true
  provider: script
  # app: intelligent-building-django
  api_key:
    secure: "3wjmwm122UprBvpzT7NkIPdo0pUFBaAL450Aj2xTzU966vKiFxl/rcjx75f7Qg9XCI5s2YlC93AKfVI1394CONoYA0TTXKRa3q+oL9rBsrgwDBU/BbO7YA7Tuoj2dF10tETufldfeahlnV1Lrk6RwVYyUgd/qTR/6Gm/UdQ82mHCJejrSPPI79bz3EJJNUFCB2++ng8gDZDXTiFmVARym4S5mfWXLapThDJLoW8SDobnhnPMU1bkIbZ0LBCEQSlt/oYX8o0yiqLatLQ4u1vVZPrN75LcbcZEqHpybYW86mzsEayzlqw3zA2iJy5MHt9WfBv44iZy7rEjnb5jgVTa3Pb486Vi7WIgEp7FAMGvmp8oupkf/qoDse2/vDDh2Gc5H/TmP2qFGBt8KAK1dFNPKg/UH/Rm56fJx2WHa8+WgBsGLqo47h/LcHRo7qblnr7XJ9ocf5aK7h+s/HsR7trjsDk8Cob9Byxo9xgyGeecXY2bVCOJ7JqzAyqiNxc7Ks/Nqxe3EzoE+7D6Aic8jn4riSAlsaW0MUJsW8NKRlPYiSIgD5rNMlA+lBGubhu/lSf2OIWR3oe1dTTnyfVbfe8QCwKvBsbqDxpCpXDvWWlN1Fc0l9fglnPLDZdjYO7ykQkHg0qlT56mFOqgXrAk2nEYPiuY+ws3yk6NQ3tpePL2iVo="
  script:
  - heroku container:push web --app intelligent-building-django
  - heroku container:release web --app intelligent-building-django
  on:
    # CI is already triggered on all branches, this triggers CD on all branches if CI was OK
    all_branches: true
